### ISSUE TITLE
No Echo response with this error

### ISSUE THREAD

**Issue by traketal** [BamaRayne/Echosistant#56]
‎Not sure if this is the kind of stuff you want, as I know this will not work because of the device handler, but for polishing purposes, ES is not giving a reply that this device does not support this command.

Blue is a virtual switch on under cabinet light setup on a H801
Handler for the virtual switch is just an on/off so it cannot be dimmed
Command I am giving Alexa is "tell main its too dark in blue"

12‎:‎54‎:‎06‎ ‎PM: error java.lang.NullPointerException: Cannot execute null+null @ line 966 
‎12‎:‎54‎:‎06‎ ‎PM: debug Received device control handler data: (deviceType)= cSwitch',(deviceCommand) = 'increase', (deviceD) = 'Blue', (unitU) = 'undefined', (numN) = '0', (delayD) = 'false' 
12:‎54‎:‎06‎ ‎PM: debug Found a device: 'Blue' 
‎12‎:‎54‎:‎06‎ ‎PM: debug Searching for a switch named 'blue' 
‎12‎:‎54‎:‎06‎ ‎PM: debug Received command data: deviceType= 'light', command= 'increase' _____>>>>> STARTING MAIN PROCESS <<<<<< ______ 
 ‎12‎:‎54‎:‎06‎ ‎PM: debug Fetching command and device type 
 ‎12‎:‎54‎:‎06‎ ‎PM: debug Received Lambda request to control devices with settings: (ctCommand)= too dark',(ctNum) = 'undefined', (ctPIN) = 'undefined', (ctDevice) = 'blue', (ctUnit) = 'undefined', (ctGroup) = 'undefined', (pintentName) = 'main' 
 ‎12‎:‎54‎:‎05‎ ‎PM: debug Message received from Lambda with: (ver) = '4.0', (date) = '12/29/2016', (release) = '4.0.0'. And sent to Lambda: pContinue = 'true', versionSTtxt = '4.0' 
‎12‎:‎54‎:‎05‎ ‎PM: debug ^^^^____Initial Commands Received from Lambda___^^^^ 

Same virtual switch, no error message spoken by alexa
"tell main to dim blue to XX%"

12:48:14 PM: error java.lang.IllegalArgumentException: Command 'setLevel' is not supported by device 671ff788-d279-48b9-aeff-48cc629446da of type 'SmartLife RGBW Virtual Switch'. Supported commands: [on, off, on, off, onPhysical, offPhysical] @ line 994 
 ‎12‎:‎48‎:‎14‎ ‎PM: debug Received device control handler data: (deviceType)= cSwitch',(deviceCommand) = 'set', (deviceD) = 'Blue', (unitU) = 'percent', (numN) = '12', (delayD) = 'false' 
 ‎12‎:‎48‎:‎14‎ ‎PM: debug Found a device: 'Blue' 
 ‎12‎:‎48‎:‎14‎ ‎PM: debug Searching for a switch named 'blue' 
‎12‎:‎48‎:‎14‎ ‎PM: debug Received command data: deviceType= 'light', command= 'set' _____>>>>> STARTING MAIN PROCESS <<<<<< ______ 
 ‎12‎:‎48‎:‎14‎ ‎PM: debug Fetching command and device type 
 ‎12‎:‎48‎:‎14‎ ‎PM: debug Received Lambda request to control devices with settings: (ctCommand)= undefined',(ctNum) = '12', (ctPIN) = 'undefined', (ctDevice) = 'blue', (ctUnit) = 'percent', (ctGroup) = 'undefined', (pintentName) = 'main' 
‎12‎:‎48‎:‎13‎ ‎PM: debug Message received from Lambda with: (ver) = '4.0', (date) = '12/29/2016', (release) = '4.0.0'. And sent to Lambda: pContinue = 'true', versionSTtxt = '4.0' 
12:‎48‎:‎13‎ ‎PM: debug ^^^^____Initial Commands Received from Lambda___^^^^

**Comment by sbdobrescu** [comment]
This is a perfect bug report. The way is designed, if you tell a switch it's too dark, but it doesn't have setlevel capabilities, it should turn on your switch. Obviously the code is looking for the current level, which is not there and the engine stops right there and fails to deliver the message to Alexa. Thanks for posting these details. I'll get it fixed right away.

**Comment by sbdobrescu** [comment]
This is fixed. Please update and try the test again. And please close the ticket if the issue was resloved :-) Thank you...

**Comment by traketal** [comment]
OK, so I updated, and if I say it is too dark or to brighter a non dimmable that is off, it will turn in on, but I am still getting no feedback from alexa on what is happening.

**Comment by sbdobrescu** [comment]
Has this been resolved? I no longer can replicate this issue after recent.

**Comment by sbdobrescu** [comment]
Hey I assume these issues have been solved. I am closing the ticket for now, if more problems pop up, please reach out. Thank you.
